In [1]:
from pathlib import Path
import pandas as pd

DOWNLOAD_DIR = Path(r"D:\Download")

# 自动找你刚下载的 en-uz tsv，避免手敲中文文件名出错
tsv_files = list(DOWNLOAD_DIR.glob("*英语*乌兹别克语*.tsv"))

print("找到的文件：")
for f in tsv_files:
    print(f)

assert len(tsv_files) > 0, "没有找到 TSV 文件"

tsv_path = tsv_files[0]

print("\n当前使用：")
print(tsv_path)

找到的文件：
D:\Download\有英语-乌兹别克语对应句 - 2026-08-20.tsv

当前使用：
D:\Download\有英语-乌兹别克语对应句 - 2026-08-20.tsv

In [2]:
raw_df = pd.read_csv(
    tsv_path,
    sep="\t",
    header=None,
    dtype=str,
    keep_default_na=False,
)

print("数据形状：", raw_df.shape)

raw_df.head(20)

数据形状： (589, 4)

,0,1,2,3
0,1563,Are they all the same?,493744,Улар ҳаммаси бир ҳилму?
1,1860,I don't want to go to school.,3633459,Мактабга боргим келмаяпти.
2,16996,Mind your own business!,423846,Ishingizni qiling!
3,16996,Mind your own business!,423847,Ishingni qil!
4,16996,Mind your own business!,423848,Ishinglarni qilinglar!
5,16996,Mind your own business!,424075,Ишингизни қилинг!
6,16996,Mind your own business!,424078,Ишингни қил!
7,16996,Mind your own business!,424079,Ишингларни қилинглар!
8,19904,The customer did not come.,2790055,Xaridor kelmadi.
9,20392,Never mind.,423857,Hech gap yo'q.
10,20392,Never mind.,424088,Ҳеч гап йўқ.
11,1636183,Every rose has its thorns.,521709,Go‘l tikansiz bo‘lmaydi.
12,23929,Do you like singing?,397111,Ашула айтиш яхши кўрасизми?
13,24579,What time do you get up?,424540,Соат нечада ўрнингиздан турибсиз?
14,24579,What time do you get up?,424541,Соат нечада ўрнингдан турибсан?
15,24657,Why didn't you come?,426599,Нима сабабдан келмадинг?
16,24657,Why didn't you come?,426601,Нима сабабдан келмадингиз?
17,24657,Why didn't you come?,426602,Нима сабабдан келмадинглар?
18,30560,"I will help you, of course.",493789,Албатта сизларга ёрдам бераман.
19,30573,Come if possible.,425125,"Мумкин бўлса, кел."

In [3]:
print("列数：", raw_df.shape[1])

for i in range(raw_df.shape[1]):
    print(f"\n===== 第 {i} 列 =====")
    print(raw_df.iloc[:10, i].tolist())

列数： 4

===== 第 0 列 =====
['1563', '1860', '16996', '16996', '16996', '16996', '16996', '16996', '19904', '20392']

===== 第 1 列 =====
['Are they all the same?', "I don't want to go to school.", 'Mind your own business!', 'Mind your own business!', 'Mind your own business!', 'Mind your own business!', 'Mind your own business!', 'Mind your own business!', 'The customer did not come.', 'Never mind.']

===== 第 2 列 =====
['493744', '3633459', '423846', '423847', '423848', '424075', '424078', '424079', '2790055', '423857']

===== 第 3 列 =====
['Улар ҳаммаси бир ҳилму?', 'Мактабга боргим келмаяпти.', 'Ishingizni qiling!', 'Ishingni qil!', 'Ishinglarni qilinglar!', 'Ишингизни қилинг!', 'Ишингни қил!', 'Ишингларни қилинглар!', 'Xaridor kelmadi.', "Hech gap yo'q."]

In [4]:
print(f"平行数据总行数：{len(raw_df):,}")

平行数据总行数：589

In [5]:
raw_df.sample(
    min(20, len(raw_df)),
    random_state=42
)

,0,1,2,3
521,11483004,Where's our daughter?,11483318,Qizimiz qayerda?
284,2255308,You will help.,3763479,Yordam berasiz.
513,7444292,They told me that they found something.,11163461,Ular menga nimadir topishganini aytishdi.
331,64956,I was hungry.,3834516,Men och edim.
210,2659524,Every colour has a meaning.,2664990,Har bir rangning ma'nosi bor.
90,410908,Where are my clocks?,423841,Soatlarim qani?
299,37744,Who do you want to speak to?,3763801,Kim bilan gaplashishni xohlaysan?
181,1097961,My dog is fast.,1223565,Itim o'zg'ir.
545,2387508,I need my keys.,12180541,Menga kalitlarim kerak.
137,473758,For health and pleasure!,473748,Соғлиқ ва лаззат учун!
546,12194491,I don't want to sign it.,12194916,Men buni imzolashni xohlamayman.
70,326004,"For example, this is a pen.",506186,"Масалан, бу ручка бўлади."
395,5295840,Come here!,3835084,Buyerga kel!
234,2543432,The mountains are beautiful.,2834770,Tog'lar go'zal.
423,1635283,We are coming.,4420925,Biz kelyapmiz.
155,528755,Health is more important than wealth.,528762,Саломатлик бойликдан муҳим.
209,2659150,Laurie broke the glass.,2661336,Lori shishani sindirdi.
576,13507064,I've got to read it.,13538320,Uni oʻqishim kerak.
503,10854332,Ziri gave a talk about the Berber language.,10854406,Ziri berber tili haqida nutq so‘zladi.
182,1097988,You are my mother.,1223568,Sen mening volidamsin.

In [6]:
df = raw_df.rename(
    columns={
        0: "en_id",
        1: "en",
        2: "uz_id",
        3: "uz",
    }
).copy()

df.head(20)

,en_id,en,uz_id,uz
0,1563,Are they all the same?,493744,Улар ҳаммаси бир ҳилму?
1,1860,I don't want to go to school.,3633459,Мактабга боргим келмаяпти.
2,16996,Mind your own business!,423846,Ishingizni qiling!
3,16996,Mind your own business!,423847,Ishingni qil!
4,16996,Mind your own business!,423848,Ishinglarni qilinglar!
5,16996,Mind your own business!,424075,Ишингизни қилинг!
6,16996,Mind your own business!,424078,Ишингни қил!
7,16996,Mind your own business!,424079,Ишингларни қилинглар!
8,19904,The customer did not come.,2790055,Xaridor kelmadi.
9,20392,Never mind.,423857,Hech gap yo'q.
10,20392,Never mind.,424088,Ҳеч гап йўқ.
11,1636183,Every rose has its thorns.,521709,Go‘l tikansiz bo‘lmaydi.
12,23929,Do you like singing?,397111,Ашула айтиш яхши кўрасизми?
13,24579,What time do you get up?,424540,Соат нечада ўрнингиздан турибсиз?
14,24579,What time do you get up?,424541,Соат нечада ўрнингдан турибсан?
15,24657,Why didn't you come?,426599,Нима сабабдан келмадинг?
16,24657,Why didn't you come?,426601,Нима сабабдан келмадингиз?
17,24657,Why didn't you come?,426602,Нима сабабдан келмадинглар?
18,30560,"I will help you, of course.",493789,Албатта сизларга ёрдам бераман.
19,30573,Come if possible.,425125,"Мумкин бўлса, кел."

In [7]:
print(df.columns.tolist())
print(df.shape)

['en_id', 'en', 'uz_id', 'uz']
(589, 4)

In [8]:
print("总数据量:", len(df))

print(
    "English 空文本:",
    (df["en"].str.strip() == "").sum()
)

print(
    "Uzbek 空文本:",
    (df["uz"].str.strip() == "").sum()
)

总数据量: 589
English 空文本: 0
Uzbek 空文本: 0

In [9]:
print(df.isna().sum())

en_id    0
en       0
uz_id    0
uz       0
dtype: int64

In [10]:
pair_duplicates = df.duplicated(
    subset=["en", "uz"]
).sum()

print("完全重复 pair:", pair_duplicates)

完全重复 pair: 0

In [11]:
print(
    "重复 English:",
    df.duplicated(subset=["en"]).sum()
)

print(
    "重复 Uzbek:",
    df.duplicated(subset=["uz"]).sum()
)

重复 English: 92
重复 Uzbek: 34

In [12]:
df = df.drop_duplicates(
    subset=["en", "uz"]
).reset_index(drop=True)

print("去重后:", len(df))

去重后: 589

In [13]:
import re

CYRILLIC_PATTERN = re.compile(
    r"[\u0400-\u04FF]"
)

def has_cyrillic(text):
    return bool(
        CYRILLIC_PATTERN.search(str(text))
    )

df["uz_has_cyrillic"] = (
    df["uz"].apply(has_cyrillic)
)

df["uz_has_cyrillic"].value_counts()

uz_has_cyrillic
False    429
True     160
Name: count, dtype: int64

In [14]:
latin_count = (~df["uz_has_cyrillic"]).sum()
cyrillic_count = df["uz_has_cyrillic"].sum()

print("Latin Uzbek:", latin_count)
print("Cyrillic Uzbek:", cyrillic_count)

print(
    "Latin比例:",
    round(latin_count / len(df) * 100, 2),
    "%"
)

print(
    "Cyrillic比例:",
    round(cyrillic_count / len(df) * 100, 2),
    "%"
)

Latin Uzbek: 429
Cyrillic Uzbek: 160
Latin比例: 72.84 %
Cyrillic比例: 27.16 %

In [15]:
cyrillic_df = df[
    df["uz_has_cyrillic"]
].copy()

cyrillic_df[
    ["en", "uz"]
].head(30)

                                      en                                    uz
0                 Are they all the same?               Улар ҳаммаси бир ҳилму?
1          I don't want to go to school.            Мактабга боргим келмаяпти.
5                Mind your own business!                     Ишингизни қилинг!
6                Mind your own business!                          Ишингни қил!
7                Mind your own business!                 Ишингларни қилинглар!
10                           Never mind.                          Ҳеч гап йўқ.
12                  Do you like singing?           Ашула айтиш яхши кўрасизми?
13              What time do you get up?     Соат нечада ўрнингиздан турибсиз?
14              What time do you get up?       Соат нечада ўрнингдан турибсан?
15                  Why didn't you come?              Нима сабабдан келмадинг?
16                  Why didn't you come?            Нима сабабдан келмадингиз?
17                  Why didn't you come?           Нима сабабдан келмадинглар?
18           I will help you, of course.       Албатта сизларга ёрдам бераман.
19                     Come if possible.                    Мумкин бўлса, кел.
20                     Come if possible.                 Мумкин бўлса, келинг.
21                     Come if possible.              Мумкин бўлса, келинглар.
22       I'll wait another five minutes.                Яна беш минут кутаман.
23  A friend in need is a friend indeed.  Қийинчиликдаги дўст ҳақиқий дўстдир.
24                    How are you, Mike?               Аҳволингиз қалай, Майк?
25                    How are you, Mike?                 Аҳволинг қалай, Майк?
27                   This is Brian Rock.                        Бу Брайан Рок.
28                    That's impossible.                            Имкон йўқ.
30                     That's my affair.                        У менинг ишим.
31                   These are my books.              Булар менинг китобларим.
33             This book belongs to you.                   Бу китоб сизга оид.
35                      That is his car.                   У унинг автомобили.
36                        Is that a cat?                           Бу мушукму?
38          Where did you see the woman?         Сиз хотинни қаерда кўрдингиз?
41                     We have no sugar.                      Бизда шакар йўқ.
42                   Is there any sugar?                          Шакар борми?

In [16]:
latin_df = df[
    ~df["uz_has_cyrillic"]
].copy()

latin_df[
    ["en", "uz"]
].head(30)

,en,uz
2,Mind your own business!,Ishingizni qiling!
3,Mind your own business!,Ishingni qil!
4,Mind your own business!,Ishinglarni qilinglar!
8,The customer did not come.,Xaridor kelmadi.
9,Never mind.,Hech gap yo'q.
11,Every rose has its thorns.,Go‘l tikansiz bo‘lmaydi.
26,Here comes the train.,Mana poezd kelyapti.
29,That's my affair.,U mening ishim.
32,This is your only chance.,Bu sening yagona imkoniyating.
34,You are drunk!,Qotibqobsanku!
37,That is mine.,U mening.
39,When do you study?,Qachon o'qiysan?
40,Aren't you thirsty?,Chanqamadingizmi?
48,I am pregnant.,Ikkiqatman.
49,I think she is a good dancer.,O'ylashimcha u yaxshi o'yinchi
54,I'll wait for you.,Seni kutaman.
57,Who stole the apple?,Olmani kim o'g'irladi?
59,He is not a doctor.,U doktor emas.
68,My father painted the mailbox red.,Otam pochta qutisini qizilga bo'yadi.
69,The post office is the brown building.,Pochta qo'ng'ir bino.
71,Good evening.,Hayirli kech.
72,I don't know.,Bilmayman.
74,What happened?,Nima gap?
77,I don't understand.,Tushunmayman.
78,Life's a ruin without you.,Sensiz hayot barbod.
80,What's the matter?,Nima bo'ldi?
82,"Don't wilt away, love.","Hazon bo'lma, muhabbat."
84,"Hello, world!",Salom dunyo!
85,Do you understand me?,Siz mening tushunayapsizmi?
87,Where are my watches?,Soatlarim qani?

In [20]:
from pathlib import Path

PROJECT_ROOT = Path(r"D:\dev\projects\fourlang_translation")

RAW_DIR = PROJECT_ROOT / "data" / "raw" / "en_uz"
CLEAN_DIR = PROJECT_ROOT / "data" / "clean" / "en_uz"
APPROVED_DIR = PROJECT_ROOT / "data" / "approved" / "en_uz"
BENCHMARK_DIR = PROJECT_ROOT / "data" / "benchmark"

for directory in [
    RAW_DIR,
    CLEAN_DIR,
    APPROVED_DIR,
    BENCHMARK_DIR,
]:
    directory.mkdir(parents=True, exist_ok=True)

print("RAW_DIR      =", RAW_DIR)
print("CLEAN_DIR    =", CLEAN_DIR)
print("APPROVED_DIR =", APPROVED_DIR)
print("BENCHMARK_DIR=", BENCHMARK_DIR)

RAW_DIR      = D:\dev\projects\fourlang_translation\data\raw\en_uz
CLEAN_DIR    = D:\dev\projects\fourlang_translation\data\clean\en_uz
APPROVED_DIR = D:\dev\projects\fourlang_translation\data\approved\en_uz
BENCHMARK_DIR= D:\dev\projects\fourlang_translation\data\benchmark

In [21]:
latin_df.to_csv(
    CLEAN_DIR / "tatoeba_en_uz_latin.csv",
    index=False,
    encoding="utf-8-sig",
)

cyrillic_df.to_csv(
    CLEAN_DIR / "tatoeba_en_uz_cyrillic.csv",
    index=False,
    encoding="utf-8-sig",
)

print("Latin Uzbek 保存完成：")
print(CLEAN_DIR / "tatoeba_en_uz_latin.csv")

print("\nCyrillic Uzbek 保存完成：")
print(CLEAN_DIR / "tatoeba_en_uz_cyrillic.csv")

Latin Uzbek 保存完成：
D:\dev\projects\fourlang_translation\data\clean\en_uz\tatoeba_en_uz_latin.csv

Cyrillic Uzbek 保存完成：
D:\dev\projects\fourlang_translation\data\clean\en_uz\tatoeba_en_uz_cyrillic.csv

In [19]:
df["en_chars"] = df["en"].str.len()
df["uz_chars"] = df["uz"].str.len()

df[
    ["en_chars", "uz_chars"]
].describe()

         en_chars    uz_chars
count  589.000000  589.000000
mean    24.711375   24.468591
std     12.956950   13.987523
min      3.000000    3.000000
25%     18.000000   16.000000
50%     23.000000   22.000000
75%     28.000000   29.000000
max    206.000000  224.000000