In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
import re
import random
import hashlib

In [2]:
PROJECT_ROOT = Path(
    r"D:\dev\projects\fourlang_translation"
)


RAW_DIR = (
    PROJECT_ROOT
    /
    "data"
    /
    "raw"
    /
    "en_uz"
)


OUTPUT_DIR = (
    PROJECT_ROOT
    /
    "data"
    /
    "clean"
    /
    "en_uz"
    /
    "exp2"
)


OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

In [3]:
hplt_df = pd.read_csv(
    PROJECT_ROOT
    /
    "data"
    /
    "clean"
    /
    "en_uz"
    /
    "hplt"
    /
    "hplt_en_uz_10k_clean.csv"
)


hplt_df.head()

,pair_id,en,uz,en_sentence_id,uz_sentence_id,src_doc_id,tgt_doc_id,lang_pair,aligner_score,bicleaner_score,bifixer_score,dataset,dataset_revision,en_chars,uz_chars
0,hplt_00000000,"Good place, where you can wait for the, that w...","Yaxshi joy, qaerda kutish mumkin, bu hech qach...",5.9,5.5,http___8cosmos.com_en_moskow__1.xml,http___8cosmos.com_uz_moskow__1.xml,en-uz,0.632494,0.999,0.9159,HPLT/DocHPLT,1c94ae042138c768caccb3cbc27f5d974a66ea0f,63,59
1,hplt_00000001,- Faculty of Engineering,- Quruvchilik fakulteti,6.1,6.1,http___en.wikipedia.org_wiki_British_Universit...,http___uz.wikipedia.org_wiki_Riga_texnika_univ...,en-uz,0.549205,0.980,0.9502,HPLT/DocHPLT,1c94ae042138c768caccb3cbc27f5d974a66ea0f,24,23
2,hplt_00000002,- They live mainly in woodland and forest regi...,- Ular asosan o'rmon va o'rmon mintaqalarida i...,7.1,7.1,https___gh.dualjuridik.org_136-lacertilles.htm...,https___uz.dualjuridik.org_136-lacertilles.htm...,en-uz,0.836660,0.987,0.9340,HPLT/DocHPLT,1c94ae042138c768caccb3cbc27f5d974a66ea0f,50,65
3,hplt_00000003,"However, species can be found in desert regions.","Biroq, turlarni cho'l hududlarida topish mumkin.",7.2,7.2,https___gh.dualjuridik.org_136-lacertilles.htm...,https___uz.dualjuridik.org_136-lacertilles.htm...,en-uz,0.836660,0.999,0.9421,HPLT/DocHPLT,1c94ae042138c768caccb3cbc27f5d974a66ea0f,48,48
4,hplt_00000004,- They have long tails and slender bodies.,- Ularning uzun quyruqlari va ingichka tanalar...,9.1,9.1,https___gh.dualjuridik.org_136-lacertilles.htm...,https___uz.dualjuridik.org_136-lacertilles.htm...,en-uz,0.816497,0.994,0.9306,HPLT/DocHPLT,1c94ae042138c768caccb3cbc27f5d974a66ea0f,42,52

In [4]:
hplt_df = hplt_df.rename(
    columns={
        "en":"src_en",
        "uz":"tgt_uz"
    }
)


hplt_df = hplt_df[
    [
        "src_en",
        "tgt_uz"
    ]
]

In [7]:
from datasets import load_dataset


dataset = load_dataset(
    "Helsinki-NLP/opus-100",
    "en-uz"
)

'[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1082)' thrown while requesting HEAD https://huggingface.co/datasets/Helsinki-NLP/opus-100/resolve/main/README.md
Retrying in 1s [Retry 1/5].

README.md:   0%|          | 0.00/65.4k [00:00<?, ?B/s]

D:\dev\projects\fourlang_translation\.venv\Lib\site-packages\huggingface_hub\file_download.py:141: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\WingYouther\.cache\huggingface\hub\datasets--Helsinki-NLP--opus-100. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

en-uz/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  222kB

en-uz/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

en-uz/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 21.4MB

en-uz/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

en-uz/validation-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  216kB

en-uz/validation-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating test split:   0%|          | 0/2000 [00:00<?, ? examples/s]

Generating train split:   0%|          | 0/173157 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/2000 [00:00<?, ? examples/s]

In [8]:
from pathlib import Path
import pandas as pd


PROJECT_ROOT = Path(
    r"D:\dev\projects\fourlang_translation"
)


SAVE_DIR = (
    PROJECT_ROOT
    /
    "data"
    /
    "raw"
    /
    "en_uz"
    /
    "opus"
)


SAVE_DIR.mkdir(
    parents=True,
    exist_ok=True
)

In [9]:
train = dataset["train"]


rows=[]


for item in train:

    rows.append(
        {
            "src_en":
                item["translation"]["en"],

            "tgt_uz":
                item["translation"]["uz"]
        }
    )


opus_df = pd.DataFrame(rows)


print(opus_df.shape)

opus_df.head()

(173157, 2)

,src_en,tgt_uz
0,Printer '%s' is out of paper.,'%s' printerda qogʻoz tugadi.
1,But surely he who bears patiently and is forgi...,Яхшилар сифати бўлган ушбу сифатларга такрор-т...
2,Intersect Paths,Obʼektlarni guruhlash
3,Lodge them where you lodge according to your m...,"Агар ҳомиладор бўлсалар, то ҳомилаларини қўйгу..."
4,"If He willed, He could still the wind, and the...","Агар У зот хоҳласа, шамолни тўхтатиб қўюр. Бас..."

In [10]:
opus_df.to_csv(
    SAVE_DIR /
    "opus100_en_uz.csv",
    index=False,
    encoding="utf-8-sig"
)

In [11]:
dataset = load_dataset(
    "Helsinki-NLP/opus-100",
    "en-uz"
)